function [x,x_pre,P,P_pre,qNk,detNk,Q,qlast] = AEkf(f,x,P,h,z,Q,R,qNk,detNk,N,qlast)
m = size(P,1);L  =size(z,1);
t = 0.05; kx = 500;ky = 500;
temp_Ak =  [1,t;0,1];
A_k = blkdiag(temp_Ak,temp_Ak,temp_Ak,temp_Ak,temp_Ak,temp_Ak);
x_pre = f(x);
P_pre = A_k*P*A_k'+Q;
% H_k=[ kx/(x_pre(5) + 25*sin(x_pre(9)) - 25*cos(x_pre(9))*sin(x_pre(11))), 0,                                          0, 0, -(kx*(x_pre(1) + 25*cos(x_pre(7))*cos(x_pre(9)) + 25*cos(x_pre(11))*sin(x_pre(7)) + 25*cos(x_pre(7))*sin(x_pre(9))*sin(x_pre(11))))/(x_pre(5) + 25*sin(x_pre(9)) - 25*cos(x_pre(9))*sin(x_pre(11)))^2, 0, -(kx*(25*cos(x_pre(9))*sin(x_pre(7)) - 25*cos(x_pre(7))*cos(x_pre(11)) + 25*sin(x_pre(7))*sin(x_pre(9))*sin(x_pre(11))))/(x_pre(5) + 25*sin(x_pre(9)) - 25*cos(x_pre(9))*sin(x_pre(11))), 0, - (kx*(25*cos(x_pre(7))*sin(x_pre(9)) - 25*cos(x_pre(7))*cos(x_pre(9))*sin(x_pre(11))))/(x_pre(5) + 25*sin(x_pre(9)) - 25*cos(x_pre(9))*sin(x_pre(11))) - (kx*(25*cos(x_pre(9)) + 25*sin(x_pre(9))*sin(x_pre(11)))*(x_pre(1) + 25*cos(x_pre(7))*cos(x_pre(9)) + 25*cos(x_pre(11))*sin(x_pre(7)) + 25*cos(x_pre(7))*sin(x_pre(9))*sin(x_pre(11))))/(x_pre(5) + 25*sin(x_pre(9)) - 25*cos(x_pre(9))*sin(x_pre(11)))^2, 0, (25*kx*cos(x_pre(9))*cos(x_pre(11))*(x_pre(1) + 25*cos(x_pre(7))*cos(x_pre(9)) + 25*cos(x_pre(11))*sin(x_pre(7)) + 25*cos(x_pre(7))*sin(x_pre(9))*sin(x_pre(11))))/(x_pre(5) + 25*sin(x_pre(9)) - 25*cos(x_pre(9))*sin(x_pre(11)))^2 - (kx*(25*sin(x_pre(7))*sin(x_pre(11)) - 25*cos(x_pre(7))*cos(x_pre(11))*sin(x_pre(9))))/(x_pre(5) + 25*sin(x_pre(9)) - 25*cos(x_pre(9))*sin(x_pre(11))), 0;
%                                           0, 0, ky/(x_pre(5) + 25*sin(x_pre(9)) - 25*cos(x_pre(9))*sin(x_pre(11))), 0, -(ky*(x_pre(3) + 25*cos(x_pre(7))*cos(x_pre(11)) - 25*cos(x_pre(9))*sin(x_pre(7)) - 25*sin(x_pre(7))*sin(x_pre(9))*sin(x_pre(11))))/(x_pre(5) + 25*sin(x_pre(9)) - 25*cos(x_pre(9))*sin(x_pre(11)))^2, 0, -(ky*(25*cos(x_pre(7))*cos(x_pre(9)) + 25*cos(x_pre(11))*sin(x_pre(7)) + 25*cos(x_pre(7))*sin(x_pre(9))*sin(x_pre(11))))/(x_pre(5) + 25*sin(x_pre(9)) - 25*cos(x_pre(9))*sin(x_pre(11))), 0,   (ky*(25*sin(x_pre(7))*sin(x_pre(9)) - 25*cos(x_pre(9))*sin(x_pre(7))*sin(x_pre(11))))/(x_pre(5) + 25*sin(x_pre(9)) - 25*cos(x_pre(9))*sin(x_pre(11))) - (ky*(25*cos(x_pre(9)) + 25*sin(x_pre(9))*sin(x_pre(11)))*(x_pre(3) + 25*cos(x_pre(7))*cos(x_pre(11)) - 25*cos(x_pre(9))*sin(x_pre(7)) - 25*sin(x_pre(7))*sin(x_pre(9))*sin(x_pre(11))))/(x_pre(5) + 25*sin(x_pre(9)) - 25*cos(x_pre(9))*sin(x_pre(11)))^2, 0, (25*ky*cos(x_pre(9))*cos(x_pre(11))*(x_pre(3) + 25*cos(x_pre(7))*cos(x_pre(11)) - 25*cos(x_pre(9))*sin(x_pre(7)) - 25*sin(x_pre(7))*sin(x_pre(9))*sin(x_pre(11))))/(x_pre(5) + 25*sin(x_pre(9)) - 25*cos(x_pre(9))*sin(x_pre(11)))^2 - (ky*(25*cos(x_pre(7))*sin(x_pre(11)) + 25*cos(x_pre(11))*sin(x_pre(7))*sin(x_pre(9))))/(x_pre(5) + 25*sin(x_pre(9)) - 25*cos(x_pre(9))*sin(x_pre(11))), 0;
%               kx/(x_pre(5) - 25*cos(x_pre(9))*sin(x_pre(11))), 0,                                          0, 0,                                   -(kx*(x_pre(1) + 25*cos(x_pre(11))*sin(x_pre(7)) + 25*cos(x_pre(7))*sin(x_pre(9))*sin(x_pre(11))))/(x_pre(5) - 25*cos(x_pre(9))*sin(x_pre(11)))^2, 0,                                    (kx*(25*cos(x_pre(7))*cos(x_pre(11)) - 25*sin(x_pre(7))*sin(x_pre(9))*sin(x_pre(11))))/(x_pre(5) - 25*cos(x_pre(9))*sin(x_pre(11))), 0,                                                                                        (25*kx*cos(x_pre(7))*cos(x_pre(9))*sin(x_pre(11)))/(x_pre(5) - 25*cos(x_pre(9))*sin(x_pre(11))) - (25*kx*sin(x_pre(9))*sin(x_pre(11))*(x_pre(1) + 25*cos(x_pre(11))*sin(x_pre(7)) + 25*cos(x_pre(7))*sin(x_pre(9))*sin(x_pre(11))))/(x_pre(5) - 25*cos(x_pre(9))*sin(x_pre(11)))^2, 0,                                                (25*kx*cos(x_pre(9))*cos(x_pre(11))*(x_pre(1) + 25*cos(x_pre(11))*sin(x_pre(7)) + 25*cos(x_pre(7))*sin(x_pre(9))*sin(x_pre(11))))/(x_pre(5) - 25*cos(x_pre(9))*sin(x_pre(11)))^2 - (kx*(25*sin(x_pre(7))*sin(x_pre(11)) - 25*cos(x_pre(7))*cos(x_pre(11))*sin(x_pre(9))))/(x_pre(5) - 25*cos(x_pre(9))*sin(x_pre(11))), 0;
%                                           0, 0,              ky/(x_pre(5) - 25*cos(x_pre(9))*sin(x_pre(11))), 0,                                   -(ky*(x_pre(3) + 25*cos(x_pre(7))*cos(x_pre(11)) - 25*sin(x_pre(7))*sin(x_pre(9))*sin(x_pre(11))))/(x_pre(5) - 25*cos(x_pre(9))*sin(x_pre(11)))^2, 0,                                   -(ky*(25*cos(x_pre(11))*sin(x_pre(7)) + 25*cos(x_pre(7))*sin(x_pre(9))*sin(x_pre(11))))/(x_pre(5) - 25*cos(x_pre(9))*sin(x_pre(11))), 0,                                                                                      - (25*ky*sin(x_pre(9))*sin(x_pre(11))*(x_pre(3) + 25*cos(x_pre(7))*cos(x_pre(11)) - 25*sin(x_pre(7))*sin(x_pre(9))*sin(x_pre(11))))/(x_pre(5) - 25*cos(x_pre(9))*sin(x_pre(11)))^2 - (25*ky*cos(x_pre(9))*sin(x_pre(7))*sin(x_pre(11)))/(x_pre(5) - 25*cos(x_pre(9))*sin(x_pre(11))), 0,                                                (25*ky*cos(x_pre(9))*cos(x_pre(11))*(x_pre(3) + 25*cos(x_pre(7))*cos(x_pre(11)) - 25*sin(x_pre(7))*sin(x_pre(9))*sin(x_pre(11))))/(x_pre(5) - 25*cos(x_pre(9))*sin(x_pre(11)))^2 - (ky*(25*cos(x_pre(7))*sin(x_pre(11)) + 25*cos(x_pre(11))*sin(x_pre(7))*sin(x_pre(9))))/(x_pre(5) - 25*cos(x_pre(9))*sin(x_pre(11))), 0;
%                                      kx/x_pre(5), 0,                                          0, 0,                                                                                                              -(kx*x_pre(1))/x_pre(5)^2, 0,                                                                                                                    0, 0,                                                                                                                                                                                                                                                               0, 0,                                                                                                                                                                                                                                              0, 0;
%                                           0, 0,                                     ky/x_pre(5), 0,                                                                                                              -(ky*x_pre(3))/x_pre(5)^2, 0,                                                                                                                    0, 0,                                                                                                                                                                                                                                                               0, 0,                                                                                                                                                                                                                                              0, 0;
%                       kx/(x_pre(5) + 25*sin(x_pre(9))), 0,                                          0, 0,                                                                        -(kx*(x_pre(1) + 25*cos(x_pre(7))*cos(x_pre(9))))/(x_pre(5) + 25*sin(x_pre(9)))^2, 0,                                                                          -(25*kx*cos(x_pre(9))*sin(x_pre(7)))/(x_pre(5) + 25*sin(x_pre(9))), 0,                                                                                                                                                   - (25*kx*cos(x_pre(9))*(x_pre(1) + 25*cos(x_pre(7))*cos(x_pre(9))))/(x_pre(5) + 25*sin(x_pre(9)))^2 - (25*kx*cos(x_pre(7))*sin(x_pre(9)))/(x_pre(5) + 25*sin(x_pre(9))), 0,                                                                                                                                                                                                                                              0, 0;
%                                           0, 0,                      ky/(x_pre(5) + 25*sin(x_pre(9))), 0,                                                                        -(ky*(x_pre(3) - 25*cos(x_pre(9))*sin(x_pre(7))))/(x_pre(5) + 25*sin(x_pre(9)))^2, 0,                                                                          -(25*ky*cos(x_pre(7))*cos(x_pre(9)))/(x_pre(5) + 25*sin(x_pre(9))), 0,                                                                                                                                                     (25*ky*sin(x_pre(7))*sin(x_pre(9)))/(x_pre(5) + 25*sin(x_pre(9))) - (25*ky*cos(x_pre(9))*(x_pre(3) - 25*cos(x_pre(9))*sin(x_pre(7))))/(x_pre(5) + 25*sin(x_pre(9)))^2, 0,                                                                                                                                                                                                                                              0, 0];

RelatObjCoor = [0 0 0;20 0 0; 20 20 0; 0 20 0];
H_k = [                                      kx/x(5), 0,                                          0, 0,                                                                                                                 -(kx*x(1))/x(5)^2, 0,                                                                                                                      0, 0,                                                                                                                                                                                                                                                                   0, 0,                                                                                                                                                                                                                                                   0, 0;
                                          0, 0,                                      ky/x(5), 0,                                                                                                                 -(ky*x(3))/x(5)^2, 0,                                                                                                                      0, 0,                                                                                                                                                                                                                                                                   0, 0,                                                                                                                                                                                                                                                   0, 0;
                       kx/(x(5) + 20*sin(x(9))), 0,                                          0, 0,                                                                           -(kx*(x(1) + 20*cos(x(7))*cos(x(9))))/(x(5) + 20*sin(x(9)))^2, 0,                                                                             -(20*kx*cos(x(9))*sin(x(7)))/(x(5) + 20*sin(x(9))), 0,                                                                                                                                                         - (20*kx*cos(x(7))*sin(x(9)))/(x(5) + 20*sin(x(9))) - (20*kx*cos(x(9))*(x(1) + 20*cos(x(7))*cos(x(9))))/(x(5) + 20*sin(x(9)))^2, 0,                                                                                                                                                                                                                                                   0, 0;
                                          0, 0,                       ky/(x(5) + 20*sin(x(9))), 0,                                                                           -(ky*(x(3) - 20*cos(x(9))*sin(x(7))))/(x(5) + 20*sin(x(9)))^2, 0,                                                                             -(20*ky*cos(x(7))*cos(x(9)))/(x(5) + 20*sin(x(9))), 0,                                                                                                                                                           (20*ky*sin(x(7))*sin(x(9)))/(x(5) + 20*sin(x(9))) - (20*ky*cos(x(9))*(x(3) - 20*cos(x(9))*sin(x(7))))/(x(5) + 20*sin(x(9)))^2, 0,                                                                                                                                                                                                                                                   0, 0;
 kx/(x(5) + 20*sin(x(9)) - 20*cos(x(9))*sin(x(11))), 0,                                          0, 0, -(kx*(x(1) + 20*cos(x(7))*cos(x(9)) + 20*cos(x(11))*sin(x(7)) + 20*cos(x(7))*sin(x(9))*sin(x(11))))/(x(5) + 20*sin(x(9)) - 20*cos(x(9))*sin(x(11)))^2, 0, -(kx*(20*cos(x(9))*sin(x(7)) - 20*cos(x(7))*cos(x(11)) + 20*sin(x(7))*sin(x(9))*sin(x(11))))/(x(5) + 20*sin(x(9)) - 20*cos(x(9))*sin(x(11))), 0, - (kx*(20*cos(x(7))*sin(x(9)) - 20*cos(x(7))*cos(x(9))*sin(x(11))))/(x(5) + 20*sin(x(9)) - 20*cos(x(9))*sin(x(11))) - (kx*(20*cos(x(9)) + 20*sin(x(9))*sin(x(11)))*(x(1) + 20*cos(x(7))*cos(x(9)) + 20*cos(x(11))*sin(x(7)) + 20*cos(x(7))*sin(x(9))*sin(x(11))))/(x(5) + 20*sin(x(9)) - 20*cos(x(9))*sin(x(11)))^2, 0, (20*kx*cos(x(9))*cos(x(11))*(x(1) + 20*cos(x(7))*cos(x(9)) + 20*cos(x(11))*sin(x(7)) + 20*cos(x(7))*sin(x(9))*sin(x(11))))/(x(5) + 20*sin(x(9)) - 20*cos(x(9))*sin(x(11)))^2 - (kx*(20*sin(x(7))*sin(x(11)) - 20*cos(x(7))*cos(x(11))*sin(x(9))))/(x(5) + 20*sin(x(9)) - 20*cos(x(9))*sin(x(11))), 0;
                                          0, 0, ky/(x(5) + 20*sin(x(9)) - 20*cos(x(9))*sin(x(11))), 0, -(ky*(x(3) + 20*cos(x(7))*cos(x(11)) - 20*cos(x(9))*sin(x(7)) - 20*sin(x(7))*sin(x(9))*sin(x(11))))/(x(5) + 20*sin(x(9)) - 20*cos(x(9))*sin(x(11)))^2, 0, -(ky*(20*cos(x(7))*cos(x(9)) + 20*cos(x(11))*sin(x(7)) + 20*cos(x(7))*sin(x(9))*sin(x(11))))/(x(5) + 20*sin(x(9)) - 20*cos(x(9))*sin(x(11))), 0,   (ky*(20*sin(x(7))*sin(x(9)) - 20*cos(x(9))*sin(x(7))*sin(x(11))))/(x(5) + 20*sin(x(9)) - 20*cos(x(9))*sin(x(11))) - (ky*(20*cos(x(9)) + 20*sin(x(9))*sin(x(11)))*(x(3) + 20*cos(x(7))*cos(x(11)) - 20*cos(x(9))*sin(x(7)) - 20*sin(x(7))*sin(x(9))*sin(x(11))))/(x(5) + 20*sin(x(9)) - 20*cos(x(9))*sin(x(11)))^2, 0, (20*ky*cos(x(9))*cos(x(11))*(x(3) + 20*cos(x(7))*cos(x(11)) - 20*cos(x(9))*sin(x(7)) - 20*sin(x(7))*sin(x(9))*sin(x(11))))/(x(5) + 20*sin(x(9)) - 20*cos(x(9))*sin(x(11)))^2 - (ky*(20*cos(x(7))*sin(x(11)) + 20*cos(x(11))*sin(x(7))*sin(x(9))))/(x(5) + 20*sin(x(9)) - 20*cos(x(9))*sin(x(11))), 0;
              kx/(x(5) - 20*cos(x(9))*sin(x(11))), 0,                                          0, 0,                                   -(kx*(x(1) + 20*cos(x(11))*sin(x(7)) + 20*cos(x(7))*sin(x(9))*sin(x(11))))/(x(5) - 20*cos(x(9))*sin(x(11)))^2, 0,                                    (kx*(20*cos(x(7))*cos(x(11)) - 20*sin(x(7))*sin(x(9))*sin(x(11))))/(x(5) - 20*cos(x(9))*sin(x(11))), 0,                                                                                        (20*kx*cos(x(7))*cos(x(9))*sin(x(11)))/(x(5) - 20*cos(x(9))*sin(x(11))) - (20*kx*sin(x(9))*sin(x(11))*(x(1) + 20*cos(x(11))*sin(x(7)) + 20*cos(x(7))*sin(x(9))*sin(x(11))))/(x(5) - 20*cos(x(9))*sin(x(11)))^2, 0,                                                (20*kx*cos(x(9))*cos(x(11))*(x(1) + 20*cos(x(11))*sin(x(7)) + 20*cos(x(7))*sin(x(9))*sin(x(11))))/(x(5) - 20*cos(x(9))*sin(x(11)))^2 - (kx*(20*sin(x(7))*sin(x(11)) - 20*cos(x(7))*cos(x(11))*sin(x(9))))/(x(5) - 20*cos(x(9))*sin(x(11))), 0;
                                          0, 0,              ky/(x(5) - 20*cos(x(9))*sin(x(11))), 0,                                   -(ky*(x(3) + 20*cos(x(7))*cos(x(11)) - 20*sin(x(7))*sin(x(9))*sin(x(11))))/(x(5) - 20*cos(x(9))*sin(x(11)))^2, 0,                                   -(ky*(20*cos(x(11))*sin(x(7)) + 20*cos(x(7))*sin(x(9))*sin(x(11))))/(x(5) - 20*cos(x(9))*sin(x(11))), 0,                                                                                      - (20*ky*sin(x(9))*sin(x(11))*(x(3) + 20*cos(x(7))*cos(x(11)) - 20*sin(x(7))*sin(x(9))*sin(x(11))))/(x(5) - 20*cos(x(9))*sin(x(11)))^2 - (20*ky*cos(x(9))*sin(x(7))*sin(x(11)))/(x(5) - 20*cos(x(9))*sin(x(11))), 0,                                                (20*ky*cos(x(9))*cos(x(11))*(x(3) + 20*cos(x(7))*cos(x(11)) - 20*sin(x(7))*sin(x(9))*sin(x(11))))/(x(5) - 20*cos(x(9))*sin(x(11)))^2 - (ky*(20*cos(x(7))*sin(x(11)) + 20*cos(x(11))*sin(x(7))*sin(x(9))))/(x(5) - 20*cos(x(9))*sin(x(11))), 0];

nq = size(qNk,2);

det = A_k*P*A_k';
temp_k = H_k*P_pre*H_k'+ R;
K = P_pre*H_k'/temp_k;
z_pre = h(x_pre);
x = x_pre + K*(z - z_pre);
P = P_pre-K*H_k*P_pre;
det = det-P;
q = x-x_pre;
qNk(:,nq+1) = q;
qbal = qlast + 1/N*(q - qNk(:,nq-N+1));

Q = Q+1/(N-1)*((q-qbal)*(q-qbal)'-(qNk(:,nq-N+1)-qbal)*(qNk(:,nq-N+1)-qbal)'+1/N*(q - qNk(:,nq-N+1))*(q - qNk(:,nq-N+1))'+(N-1)/N*(detNk((m*(nq-1)+1):(m*nq),1:m)-det));
detNk = [detNk;det];
qlast = qbal;